### ISSUE TITLE
Awesome post!

### ISSUE THREAD

**Issue by iMikie** [amberzilla/amberzilla.github.io#2]
Totally pro.
1) it's high quality.  I wish I could tell  you to go be a journalist instead.
2) "cycle"??????  I didn't know that existed. 
3) You found an interesting example and made it entertaining.  I think I want to follow your blog now.  
So pat yourself on the back for all that!  There is nothing negative I can say about the post.

**Comment by amberzilla** [comment]
Aww thanks Mike, I really appreciate your kind words and positive feedback!
